// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xghomfwfvivjbmwyvgxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnaG9tZndmdml2amJtd3l2Z3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDg4NzEsImV4cCI6MjA3Mzg4NDg3MX0.bgWTLw-X2bYXEcuvdh40nYKD5q15secjbkFsqc4cFJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});